USERNAME: 'username123'
PASSWORD: 'example123'
TAGS: [ 'human', 'life', 'humanphotography', 'sunset', 'nature', 'sky', 'clouds', 'sun', 'moon', 'rural', 'supermoon' ]
TOTAL_LIKES: 200
LIKES_PER_USER: 2
